name: Approval Check

on:
  workflow_call:
    inputs:
      env_name:
        description: "Environment Name (DEV or SIT)"
        required: true
        type: string

jobs:
  check-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Log Environment
        run: |
          echo "Checking for approval in environment: ${{ inputs.env_name }}"
      # You can add more steps here to simulate or check for approval
