name: Wait for Approval

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string

jobs:
  wait-for-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Log Environment
        run: echo "Waiting for approval in environment ${{ inputs.env_name }}"

      - name: Wait for Webhook Trigger
        run: |
          while true; do
            if [ -f /tmp/approval_received ]; then
              echo "Approval received for ${{ inputs.env_name }}!"
              break
            fi
            echo "No approval yet for ${{ inputs.env_name }}. Waiting..."
            sleep 60
          done
          
        timeout-minutes: 0
