name: Send Approval Email

on:
  workflow_call:
    inputs:
      env_name:
        description: 'The environment name (e.g., DEV, SIT)'
        required: true
        type: string
      approval_email:
        description: 'The email address to send approval to'
        required: true
        type: string
      email_subject:
        description: 'Subject of the email'
        required: true
        type: string
      email_body:
        description: 'Body of the email'
        required: true
        type: string

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Approval Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          subject: ${{ inputs.email_subject }}
          body: ${{ inputs.email_body }}
          to: ${{ inputs.approval_email }}
          attachments: |
            reports/extent-report.html
            reports/screenshots/*
